#!/bin/bash
# install discord

# install with .deb
wget -O discord.deb "https://discordapp.com/api/download?platform=linux&format=deb"
sudo dpkg -i discord.deb

# using snap to support discord updates
# sudo snap install discord
